version: 2

jobs:
  build:
    working_directory: ~/hxenv
    docker:
      - image: haxe:3.4
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: apt-get update && apt-get upgrade -y && apt-get install -y gcc g++ openjdk-7-jdk
      - run:
          name: Install dependency hxcpp
          command: haxelib install --always hxcpp 3.4.64
      - run:
          name: Install dependency hxjava
          command: haxelib install --always hxjava 3.2.0
      - run:
          name: Install dependency mcli
          command: haxelib install --always mcli 0.1.6
      - run:
          name: Build project
          command: haxe build.hxml